### ISSUE TITLE
发生同样的错误

### ISSUE THREAD

**Issue by ClayMoreBoy** [ylqjgm/OpenWRT#2]
Input required and not supplied: upload_url
https://github.com/ClayMoreBoy/OpenWrt-Actions-R7800/runs/562123684?check_suite_focus=true

**Comment by ylqjgm** [comment]
给 actions/create-release 一个 id，后面的上传使用 create-release 输出的 upload_url

**Comment by ClayMoreBoy** [comment]
你修改一下你的脚本我看看 增加ID就完事吗？

**Comment by ClayMoreBoy** [comment]
已解决 加了ID生效
